- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
    - name: Update Homebrew and Upgrade All Packages
      community.general.homebrew:
        update_homebrew: yes
        upgrade_all: yes
  tasks:
    - import_tasks: tasks/ssh.yml
      tags: ["ssh", "dotfiles"]
    - import_tasks: tasks/dotfiles.yml
      tags: ["dotfiles"]
    - import_tasks: tasks/rustup.yml
      tags: ["rust", "cargo", "shell", "utils"]
    - import_tasks: tasks/fonts.yml
      tags: ["fonts", "shell"]
    - import_tasks: tasks/shell.yml
      tags: ["shell"]
    - import_tasks: tasks/tmux.yml
      tags: ["tmux", "zsh"]
    - import_tasks: tasks/nvm.yml
      tags: ["nvm", "node", "zsh"]
    - import_tasks: tasks/zsh.yml
      tags: ["zsh"]
    - import_tasks: tasks/hammerspoon.yml
      tags: ["hammerspoon"]
    - import_tasks: tasks/kitty.yml
      tags: ["kitty"]
    - import_tasks: tasks/neovim.yml
      tags: ["neovim"]
    - import_tasks: tasks/cli-utils.yml
      tags: ["cli", "neovim"]
    - import_tasks: tasks/git.yml
      tags: ["git"]
    - import_tasks: tasks/brave.yml
      tags: ["brave", "browsers"]
    - import_tasks: tasks/discord.yml
      tags: ["discord", "chat"]
    - import_tasks: tasks/docker.yml
      tags: ["docker"]
    - import_tasks: tasks/postman.yml
      tags: ["postman"]
    - import_tasks: tasks/kafka.yml
      tags: ["kafka"]
    - import_tasks: tasks/system-preferences.yml
      tags: ["system-preferences"]
