- name: Install Stow
  community.general.homebrew:
    name: stow
    state: present
- name: Clone dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:jordanfjellman/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/code/jordanfjellman/dotfiles"
- name: Stow dotfiles
  shell: cd "{{ lookup('env', 'HOME') }}/code/jordanfjellman/dotfiles" && ./install

