- name: Install Kitty
  community.general.homebrew:
    name: kitty
    state: present
  tags:
    - install
    - kitty
    - dotfiles
- name: Install Theme
  shell: curl -O ~/.config/kitty/theme.conf https://raw.githubusercontent.com/projekt0n/github-nvim-theme/main/extras/kitty/dimmed.conf
  tags:
    - install
    - kitty
    - dotfiles
