- name: Install Kitty
  community.general.homebrew_cask:
    name: kitty
- name: Download "Github Dimmed" Theme
  shell: curl --create-dirs --output {{ lookup('env', 'HOME') }}/.config/kitty/themes/github_dimmed.conf https://raw.githubusercontent.com/projekt0n/github-nvim-theme/main/terminal/kitty/github_dimmed.conf

