- name: Install Neovim
  community.general.homebrew:
    name: neovim
- name: Clone Packer to `packpath`
  ansible.builtin.git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    depth: 1

