- name: Check if Cargo is Already Installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: true
- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
- name: Install Rust and Cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
- name: Install sccache to Improve Compile Times
  community.general.cargo:
    name: sccache
- name: Install rustfmt
  shell: rustup component add rustfmt
- name: Install graphviz # for crate graph
  community.general.homebrew:
    name: graphviz
