- name: Install Nushell
  community.general.cargo:
    name: nu
- name: Install CoreUtils for Cross-Shell Compatible Scripting
  community.general.cargo:
    name: coreutils
- name: Install Sharship
  community.general.cargo: name={{ item }}
  with_items:
    - cmake  # required for starship install
    - starship
