- name: Ensure .ssh Directory Exists
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
- name: Install SSH Key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
- name: Set Public SSH Key
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
- name: Set Authorized Key
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"

