- name: Install Tmux
  community.general.homebrew:
    name: tmux
- name: Install TPM (Tmux Plugin Manager)
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
- name: Install reattach-to-user-namespace
  community.general.homebrew:
    name: reattach-to-user-namespace

# Don't forget to install the plugins! `prefix + I`

